/*
 * base.h
 *
 *  Created on: Jul 15, 2025
 *      Author: prate
 */

#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE          (0x40000000)

#define APB1_PERIPHERAL_OFFSET   (0x0000)
#define APB1_PERIPHERAL          (PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET   (0x00010000)
#define APB2_PERIPHERAL	         (PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB1_PERIPHERAL_OFFSET   (0x00020000)
#define AHB1_PERIPHERAL          (PERIPHERAL_BASE + AHB1_PERIPHERAL_OFFSET)

#define ADC_PERIPHERAL_OFFSET    (0x00002000)
#define ADC_PERIPHERAL           (APB2_PERIPHERAL + ADC_PERIPHERAL_OFFSET)

#define USART1_PERIPHERAL_OFFSET (0x00001000)
#define USART1_PERIPHERAL	     (APB2_PERIPHERAL + USART1_PERIPHERAL_OFFSET)

#define GPIOA_PERIPHERAL_OFFSET  (0x00000000)
#define GPIOA_PERIPHERAL		 (AHB1_PERIPHERAL + GPIOA_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET  (0x00000400)
#define GPIOB_PERIPHERAL         (AHB1_PERIPHERAL + GPIOB_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET  (0x00000800)
#define GPIOC_PERIPHERAL	     (AHB1_PERIPHERAL + GPIOC_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET    (0x00003800)
#define RCC_PERIPHERAL	         (AHB1_PERIPHERAL + RCC_PERIPHERAL_OFFSET)

enum State{
	OFF = 48,
	ON = 49
};

#endif /* BASE_H_ */
